feature : created film and user rest controllers
VitalyFreed/java-filmorate pull request #2
Opened 2023-03-11 16:37 UTC by VitalyFreed

2023-03-12 16:59 UTC, ErkinKasymaliev requested changes
привет, оставил комменты, и тесты постмана не проходят, надо чтобы сборка была полностью зеленой

2023-03-12 16:59 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    double duration;
почему не private?

2023-03-12 16:59 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        for (User userItem : users.values()) {
можно валидацию полностью сделать через аннотации в классе модели

2023-03-22 13:46 UTC, VitalyFreed commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        for (User userItem : users.values()) {
Не совсем понял как это

2023-03-29 03:23 UTC, closed without merging